spring:
  application:
    name: spring-authentication-server

  web:
    resources:
      static-locations:
        - file:C:/video-streaming-over-quic/vsoq.react.auth/

  # User DB Settings
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: choi
    password: root
    driver-class-name: org.postgresql.Driver

  # JPA Settings
  jpa:
    hibernate:
      ddl-auto: update     # 개발 중엔 update, 운영 시엔 validate 권장
    show-sql: true         # (선택) 쿼리 로깅
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


  # Authorization Server Endpoint Settings
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000
        endpoint:
          authorization-uri: /oauth2/authorize
          token-uri: /oauth2/token
          token-revocation-uri: /oauth2/revoke
          jwk-set-uri: /oauth2/jwks
          oidc:
            client-registration-uri: /connect/register
            userinfo-uri: /connect/userinfo
            logout-uri: /connect/logout
#          token-introspection-uri: /oauth2/introspect


# Authentication Server Basic port
server:
  port: 9000

logging:
  level:
    org.springframework.security.oauth2.server.authorization: DEBUG
    org.springframework.security.web: DEBUG